#!/bin/bash

# Ruta del archivo temporal para almacenar la respuesta
response_file="/tmp/response.txt"

# Actualizar la lista de paquetes
apt update > /dev/null

# Obtener la lista de paquetes actualizables
updates=$(apt list --upgradable 2>/dev/null | grep -v -E "(Listing|apt-utils|grep)")

# Comprobar si hay actualizaciones disponibles
if [ -z "$updates" ]; then
    echo "No hay actualizaciones disponibles."
else
    echo "Hay actualizaciones pendientes de los paquetes:"
    echo "$updates"
fi

# Enviar correo electrónico a root
echo "Actualización de APT:
$updates" | mail -s "Informe de actualización de APT" root

# Leer la respuesta del usuario desde el correo electrónico
echo "Por favor, responda al correo electrónico con 'yes' o 'no' y luego presione Ctrl+D para enviar."
cat > "$response_file"

# Procesar la respuesta del usuario
response=$(cat "$response_file" | tr -d '\n' | tr '[:upper:]' '[:lower:]')

# Si el usuario responde 'yes', proceder con la actualización
if [ "$response" = "yes" ]; then
    apt upgrade -y
fi

# Eliminar el archivo temporal de respuesta
rm "$response_file" >/dev/null 2>&1



#mediante cron. Puedes agregarlo a la lista de tareas cron con el comando crontab -e y añadiendo esta linea:

0 2 * * * /ruta/al/script.sh
